### ISSUE TITLE
[Feature Request] Async `generateStateFunction`

### ISSUE THREAD

**Issue by NotEvenANeko** [fastify/fastify-oauth2#238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

`generateStateFunction` can return a `Promise<string>`

### Motivation

I need to store the generated state in external databases like redis, and async operation is required here. But now the return value of `generateStateFunction` is directly passed to `reply.setCookie`.

### Example

```typescript
 fastify.register(oauthPlugin, {
   ...
   generateStateFunction: async (request) => {
      const [state, ctx] = await randomState();
      await redis.set(state, ctx);
      return state;
   }
 })
```

**Comment by Eomm** [comment]
I think this could be doable with an `onRequest` hook:

- request comes in
- hook generate a sessionId and attach it to the request
- the `generateStateFunction` reads the sessionId and returns it

Anyway, this could be interesting to support.
One think to mention is that the `generateStateFunction` should get the fastify instance as `this` context - otherwise, it will be hard to access the db.

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by NotEvenANeko** [comment]
Sure, I'll try this.
