### ISSUE TITLE
How do I create a protected endpoint?

### ISSUE THREAD

**Issue by TheKnarf** [fastify/fastify-oauth2#253]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

How do I mark a fastify enpoint as protected, so that only authenticated users can access it?

I can't seem to see it in the docs, nor in it he examples.

**Comment by TheKnarf** [comment]
There is a lot of moving parts that all are supposed to work together. It would be really useful with a more complete example that:

- Show how to use `fastify-oauth2` and `fastify/session` together
- Shows how to protect an endpoint with `Encapsulation` and `fastify/session`
- Shows how the protected endpoint is supposed to handle:
    - Verifying the token
    - Validating that the token isn't expired
    - Refresh the token using the refresh token if needed

Right now it feels like I'm trying to piece together a puzzle by reading a bunch of different documentation, non of which show a complete example.

**Comment by climba03003** [comment]
> And its not clear to me if I'm supposed to use preValidation or Encapsulation for a protected endpoint?

Don't overthink too much, hooks are just function to run at designed time.
Encapsulation is only used for better manage your routes.

That being said, if you need to protect a single route only, pass the protect function to `route` option.
If you need to protect a bunch of routes, using encapsulation with `fastify.addHook` would be much simpler.

In all case using the same hook `preValidation`.

> It would be really useful with a more complete example

It is hard for us to create example if requests. Most of them depends on user-case and not fit for all people.
You should understand what you need and find the appropriate plugin.

From what I can see now is that, you should not use `@fastify/oauth` because it is used for `OAuth2.0` integration of other platform.
Instead, a simple solution is using `@fastify/session` alone and write the user authenticated state after login.

If you need made a RESTful API, you may also consider using `@fastify/jwt` to provide access token to client.
The client should store the access token to appropriate place and send it to server in every request.

**Comment by TheKnarf** [comment]
Thanks, that clarifies a bit.

I'm building an app that consist of an React SPA and a Fastify backend-for-frontend service that needs to integrate with an external OAuth provider for authenticating users, and then a separate backend maintained by another team in C#. So thats why I'm trying to get oauth + session storage working together.

I guess that means I need to implement my own  `preValidation`, and in that somehow validate that the token is still valid as well as calling `getNewAccessTokenUsingRefreshToken` to keep it alive?

**Comment by climba03003** [comment]
> I guess that means I need to implement my own preValidation, and in that somehow validate that the token is still valid as well as calling getNewAccessTokenUsingRefreshToken to keep it alive?

The idea is correct.
You should save both refresh token and access token in this case inside the session.

Inside the `preValidation`, you should validate both the `access token` and `refresh token` expiration time.
When both expire or invalid, you should signout the user.
When only the `access token` expire or invalid, try to get a new one using the `refresh token`

The invalid means you should call the backend using the `access token` to see if the token revoked in the backend.

**Comment by NullVoxPopuli** [comment]
I'm new to fastify, and i'm finding I have a lot of the same questions. :sweat_smile:
